import { useState } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { HelpCircle, ArrowLeft, ArrowRight, CheckCircle2, AlertTriangle, XCircle, RefreshCw, Copy, Check } from "lucide-react";
import { toast } from "sonner";

interface WizardStep {
  id: string;
  question: string;
  options: {
    label: string;
    value: string;
    icon?: React.ReactNode;
  }[];
}

interface Solution {
  title: string;
  severity: "success" | "warning" | "error";
  description: string;
  steps: string[];
  codeSnippet?: string;
}

const wizardSteps: WizardStep[] = [
  {
    id: "error_type",
    question: "What type of error are you seeing in Make.com?",
    options: [
      { label: "Connection error / timeout", value: "connection", icon: <XCircle className="h-4 w-4" /> },
      { label: "Signature validation failed (401/403)", value: "signature", icon: <AlertTriangle className="h-4 w-4" /> },
      { label: "Invalid payload / parsing error", value: "payload", icon: <AlertTriangle className="h-4 w-4" /> },
      { label: "Module configuration error", value: "config", icon: <HelpCircle className="h-4 w-4" /> },
      { label: "Scenario runs but webhook not received", value: "not_received", icon: <RefreshCw className="h-4 w-4" /> },
    ],
  },
  {
    id: "signature_detail",
    question: "Where do you think the signature issue is?",
    options: [
      { label: "Signature doesn't match at all", value: "mismatch" },
      { label: "Using the wrong secret key", value: "wrong_key" },
      { label: "Payload format seems different", value: "payload_format" },
      { label: "Not sure / need to debug", value: "debug" },
    ],
  },
  {
    id: "connection_detail",
    question: "What specific connection issue are you seeing?",
    options: [
      { label: "Request timed out", value: "timeout" },
      { label: "Could not resolve host", value: "dns" },
      { label: "Connection refused", value: "refused" },
      { label: "SSL/TLS error", value: "ssl" },
    ],
  },
  {
    id: "payload_detail",
    question: "What payload error are you seeing?",
    options: [
      { label: "Invalid JSON syntax", value: "json_syntax" },
      { label: "Missing required fields", value: "missing_fields" },
      { label: "Wrong content type", value: "content_type" },
      { label: "Payload too large", value: "too_large" },
    ],
  },
  {
    id: "config_detail",
    question: "Which module is showing the configuration error?",
    options: [
      { label: "Set Variable (Payload)", value: "set_payload" },
      { label: "Set Variable (Timestamp)", value: "set_timestamp" },
      { label: "Encryptor → Sign", value: "encryptor" },
      { label: "HTTP → Make a Request", value: "http" },
    ],
  },
  {
    id: "not_received_detail",
    question: "Can you confirm the scenario ran successfully?",
    options: [
      { label: "Yes, all modules show green checkmarks", value: "success" },
      { label: "Some modules show warnings", value: "warnings" },
      { label: "HTTP module shows success but no data on server", value: "http_success" },
      { label: "Not sure how to check", value: "unsure" },
    ],
  },
];

const getSolutions = (answers: Record<string, string>): Solution[] => {
  const solutions: Solution[] = [];

  // Signature issues
  if (answers.error_type === "signature") {
    if (answers.signature_detail === "mismatch") {
      solutions.push({
        title: "Signature Mismatch",
        severity: "error",
        description: "The signature generated by Make.com doesn't match what the server expects. This is usually caused by payload formatting differences.",
        steps: [
          "In Make.com, ensure the Set Variable (Payload) module outputs a SINGLE-LINE JSON string",
          "Remove all line breaks and extra whitespace from your payload",
          "Verify the Encryptor → Sign module uses the exact same payload variable: {{2.payload}}",
          "Check that the HTTP module body also uses {{2.payload}} (not a reformatted version)",
          "Use the Debug Signature Tool on this page to verify the expected hash",
        ],
        codeSnippet: '{"eventType": "order.created", "orderId": "123", "total": 99.99}',
      });
    } else if (answers.signature_detail === "wrong_key") {
      solutions.push({
        title: "Secret Key Mismatch",
        severity: "error",
        description: "The secret key in Make.com doesn't match the key saved in your webhook configuration.",
        steps: [
          "Copy the saved private key from the 'Generate Private Key' section above",
          "In Make.com, open the Encryptor → Sign module",
          "Paste the exact key into the 'Key' field",
          "Ensure 'Key encoding' is set to 'Text'",
          "Run the scenario again",
        ],
      });
    } else if (answers.signature_detail === "payload_format") {
      solutions.push({
        title: "Payload Format Issue",
        severity: "warning",
        description: "The payload being signed differs from what's sent in the request body.",
        steps: [
          "Both the Encryptor and HTTP modules MUST reference the same payload variable",
          "Use {{2.payload}} in both modules (assuming Set Payload is module 2)",
          "Do NOT manually type the JSON in the HTTP body - always reference the variable",
          "Verify the Content-Type header is set to 'application/json'",
        ],
      });
    } else {
      solutions.push({
        title: "Debug Your Signature",
        severity: "warning",
        description: "Let's systematically debug the signature validation.",
        steps: [
          "1. Copy your payload from Make.com's Set Variable module",
          "2. Paste it into the Debug Signature Tool below",
          "3. Generate the expected signature hash",
          "4. Compare with Make.com's Encryptor output (visible in scenario execution history)",
          "5. If they match but validation still fails, check the HTTP headers are correct",
        ],
      });
    }
  }

  // Connection issues
  if (answers.error_type === "connection") {
    if (answers.connection_detail === "timeout") {
      solutions.push({
        title: "Request Timeout",
        severity: "warning",
        description: "The webhook endpoint is taking too long to respond.",
        steps: [
          "Increase the timeout in Make.com's HTTP module settings (try 60 seconds)",
          "Check if the Supabase edge function is working by testing directly",
          "Use the 'Test Webhook' button above to verify the endpoint is responsive",
          "If using a large payload, consider splitting into smaller requests",
        ],
      });
    } else if (answers.connection_detail === "dns") {
      solutions.push({
        title: "DNS Resolution Error",
        severity: "error",
        description: "Make.com cannot resolve the webhook URL.",
        steps: [
          "Verify the webhook URL is correct (copy from 'Your Webhook Endpoint' section)",
          "Ensure there are no typos in the URL",
          "Check that the Supabase project is active and not paused",
          "Try accessing the URL in a browser to confirm it's reachable",
        ],
      });
    } else if (answers.connection_detail === "refused") {
      solutions.push({
        title: "Connection Refused",
        severity: "error",
        description: "The server is actively refusing connections.",
        steps: [
          "Check if the edge function is deployed correctly",
          "Verify the Supabase project is not paused",
          "Ensure you're using the correct HTTPS URL",
          "Test the endpoint directly using the test button above",
        ],
      });
    } else {
      solutions.push({
        title: "SSL/TLS Error",
        severity: "warning",
        description: "There's a certificate or encryption issue.",
        steps: [
          "Ensure the URL starts with 'https://' (not 'http://')",
          "Make.com should handle SSL automatically - if not, contact Make.com support",
          "Verify the Supabase project URL is correct",
        ],
      });
    }
  }

  // Payload issues
  if (answers.error_type === "payload") {
    if (answers.payload_detail === "json_syntax") {
      solutions.push({
        title: "Invalid JSON Syntax",
        severity: "error",
        description: "The JSON payload has syntax errors.",
        steps: [
          "Use a JSON validator to check your payload (jsonlint.com)",
          "Ensure all strings are wrapped in double quotes (not single quotes)",
          "Check for trailing commas after the last item",
          "Escape special characters properly (backslash for quotes, etc.)",
        ],
        codeSnippet: '{"key": "value", "number": 123, "boolean": true}',
      });
    } else if (answers.payload_detail === "content_type") {
      solutions.push({
        title: "Wrong Content Type",
        severity: "warning",
        description: "The Content-Type header doesn't match the body format.",
        steps: [
          "In the HTTP module, set 'Body type' to 'Raw'",
          "Set 'Content type' to 'JSON (application/json)'",
          "Add a header: Content-Type: application/json",
          "Ensure the body is valid JSON (not form data or text)",
        ],
      });
    } else {
      solutions.push({
        title: "Payload Issue",
        severity: "warning",
        description: "There's an issue with your request payload.",
        steps: [
          "Review the required fields in the edge function",
          "Ensure all required fields are present in your payload",
          "Check for field name case sensitivity",
          "Verify field types match expectations (strings, numbers, etc.)",
        ],
      });
    }
  }

  // Config issues
  if (answers.error_type === "config") {
    if (answers.config_detail === "encryptor") {
      solutions.push({
        title: "Encryptor Module Configuration",
        severity: "warning",
        description: "The Encryptor → Sign module needs specific settings.",
        steps: [
          "Algorithm: sha256",
          "Key: [Your saved private key - copy from above]",
          "Key encoding: Text",
          "Data: {{2.payload}} (reference to Set Payload variable)",
          "Data encoding: Text",
          "Digest: Hexadecimal",
        ],
      });
    } else if (answers.config_detail === "http") {
      solutions.push({
        title: "HTTP Module Configuration",
        severity: "warning",
        description: "The HTTP → Make a Request module needs these exact settings.",
        steps: [
          "URL: [Copy from 'Your Webhook Endpoint' section]",
          "Method: POST",
          "Body type: Raw",
          "Content type: JSON (application/json)",
          "Request content: {{2.payload}}",
          "Headers: X-Webhook-Signature: {{4.value}}, X-Webhook-Timestamp: {{3.timestamp}}, Content-Type: application/json",
        ],
      });
    } else {
      solutions.push({
        title: "Variable Module Configuration",
        severity: "warning",
        description: "Set Variable modules need proper configuration.",
        steps: [
          "For Payload: Variable name = 'payload', Value = your JSON (single line)",
          "For Timestamp: Variable name = 'timestamp', Value = {{formatDate(now; \"YYYY-MM-DDTHH:mm:ssZ\")}}",
          "Ensure variables are scoped to 'roundtrip' or the default scope",
          "Module order matters! Payload first, then Timestamp, then Sign",
        ],
      });
    }
  }

  // Not received issues
  if (answers.error_type === "not_received") {
    if (answers.not_received_detail === "http_success") {
      solutions.push({
        title: "HTTP Success but No Data",
        severity: "warning",
        description: "Make.com shows success but the webhook isn't being processed.",
        steps: [
          "Check the response body from the HTTP module - is it an error JSON?",
          "Verify X-Webhook-Signature header is included (not just in body)",
          "Verify X-Webhook-Timestamp header is included",
          "Check edge function logs for any errors",
          "Run the signature validation test above to verify setup",
        ],
      });
    } else {
      solutions.push({
        title: "Webhook Delivery Issue",
        severity: "warning",
        description: "Let's verify the webhook is being sent correctly.",
        steps: [
          "Check the scenario execution history for any errors",
          "Verify the HTTP module shows a 200 status code",
          "Look at the response body for error messages",
          "Test the endpoint directly using the 'Test Signature Validation' button",
          "Check if there's a rate limit being hit",
        ],
      });
    }
  }

  return solutions;
};

export const MakeTroubleshootingWizard = () => {
  const [currentStepIndex, setCurrentStepIndex] = useState(0);
  const [answers, setAnswers] = useState<Record<string, string>>({});
  const [showSolutions, setShowSolutions] = useState(false);
  const [copied, setCopied] = useState<string | null>(null);

  const getNextStep = (currentAnswer: string): number | null => {
    const currentStep = wizardSteps[currentStepIndex];
    
    if (currentStep.id === "error_type") {
      switch (currentAnswer) {
        case "signature":
          return wizardSteps.findIndex(s => s.id === "signature_detail");
        case "connection":
          return wizardSteps.findIndex(s => s.id === "connection_detail");
        case "payload":
          return wizardSteps.findIndex(s => s.id === "payload_detail");
        case "config":
          return wizardSteps.findIndex(s => s.id === "config_detail");
        case "not_received":
          return wizardSteps.findIndex(s => s.id === "not_received_detail");
        default:
          return null;
      }
    }
    
    return null; // End of wizard
  };

  const handleAnswer = (value: string) => {
    const currentStep = wizardSteps[currentStepIndex];
    const newAnswers = { ...answers, [currentStep.id]: value };
    setAnswers(newAnswers);

    const nextStepIndex = getNextStep(value);
    if (nextStepIndex !== null && nextStepIndex !== -1) {
      setCurrentStepIndex(nextStepIndex);
    } else {
      setShowSolutions(true);
    }
  };

  const handleBack = () => {
    if (showSolutions) {
      setShowSolutions(false);
    } else if (currentStepIndex > 0) {
      // Go back to first step for simplicity
      setCurrentStepIndex(0);
      setAnswers({});
    }
  };

  const handleReset = () => {
    setCurrentStepIndex(0);
    setAnswers({});
    setShowSolutions(false);
  };

  const copyToClipboard = async (text: string, label: string) => {
    await navigator.clipboard.writeText(text);
    setCopied(label);
    toast.success("Copied to clipboard");
    setTimeout(() => setCopied(null), 2000);
  };

  const solutions = getSolutions(answers);
  const currentStep = wizardSteps[currentStepIndex];

  return (
    <Card className="border-orange-500/20 bg-orange-500/5">
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <HelpCircle className="h-5 w-5 text-orange-500" />
          Troubleshooting Wizard
        </CardTitle>
        <CardDescription>
          Answer a few questions to get specific solutions for your Make.com webhook issues
        </CardDescription>
      </CardHeader>
      <CardContent>
        {!showSolutions ? (
          <div className="space-y-4">
            {/* Progress indicator */}
            <div className="flex items-center gap-2 text-sm text-muted-foreground">
              <span>Step {currentStepIndex === 0 ? 1 : 2} of 2</span>
              {Object.keys(answers).length > 0 && (
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={handleBack}
                  className="h-6 px-2 gap-1"
                >
                  <ArrowLeft className="h-3 w-3" />
                  Back
                </Button>
              )}
            </div>

            {/* Question */}
            <p className="text-lg font-medium">{currentStep.question}</p>

            {/* Options */}
            <div className="grid gap-2">
              {currentStep.options.map((option) => (
                <Button
                  key={option.value}
                  variant="outline"
                  className="justify-start h-auto py-3 px-4 text-left"
                  onClick={() => handleAnswer(option.value)}
                >
                  {option.icon && <span className="mr-2">{option.icon}</span>}
                  {option.label}
                  <ArrowRight className="h-4 w-4 ml-auto opacity-50" />
                </Button>
              ))}
            </div>
          </div>
        ) : (
          <div className="space-y-4">
            {/* Header with reset */}
            <div className="flex items-center justify-between">
              <Badge variant="outline" className="gap-1">
                <CheckCircle2 className="h-3 w-3" />
                Solutions Found
              </Badge>
              <Button variant="ghost" size="sm" onClick={handleReset} className="gap-1">
                <RefreshCw className="h-3 w-3" />
                Start Over
              </Button>
            </div>

            {/* Solutions */}
            <div className="space-y-4">
              {solutions.map((solution, index) => (
                <div
                  key={index}
                  className={`p-4 rounded-lg border ${
                    solution.severity === "error"
                      ? "border-red-200 bg-red-50 dark:border-red-900/50 dark:bg-red-950/20"
                      : solution.severity === "warning"
                      ? "border-yellow-200 bg-yellow-50 dark:border-yellow-900/50 dark:bg-yellow-950/20"
                      : "border-green-200 bg-green-50 dark:border-green-900/50 dark:bg-green-950/20"
                  }`}
                >
                  <div className="flex items-start gap-3">
                    {solution.severity === "error" ? (
                      <XCircle className="h-5 w-5 text-red-500 shrink-0 mt-0.5" />
                    ) : solution.severity === "warning" ? (
                      <AlertTriangle className="h-5 w-5 text-yellow-500 shrink-0 mt-0.5" />
                    ) : (
                      <CheckCircle2 className="h-5 w-5 text-green-500 shrink-0 mt-0.5" />
                    )}
                    <div className="flex-1 space-y-2">
                      <h4 className="font-semibold">{solution.title}</h4>
                      <p className="text-sm text-muted-foreground">{solution.description}</p>
                      
                      <div className="space-y-1.5">
                        <p className="text-sm font-medium">Steps to fix:</p>
                        <ol className="text-sm space-y-1 list-decimal list-inside">
                          {solution.steps.map((step, stepIndex) => (
                            <li key={stepIndex} className="text-muted-foreground">
                              {step}
                            </li>
                          ))}
                        </ol>
                      </div>

                      {solution.codeSnippet && (
                        <div className="mt-3">
                          <p className="text-sm font-medium mb-1">Example:</p>
                          <div className="flex items-center gap-2">
                            <code className="flex-1 text-xs bg-background p-2 rounded font-mono overflow-x-auto">
                              {solution.codeSnippet}
                            </code>
                            <Button
                              variant="ghost"
                              size="icon"
                              className="h-8 w-8 shrink-0"
                              onClick={() => copyToClipboard(solution.codeSnippet!, `snippet-${index}`)}
                            >
                              {copied === `snippet-${index}` ? (
                                <Check className="h-3 w-3" />
                              ) : (
                                <Copy className="h-3 w-3" />
                              )}
                            </Button>
                          </div>
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              ))}
            </div>

            {/* Back button */}
            <Button variant="outline" onClick={handleBack} className="gap-2">
              <ArrowLeft className="h-4 w-4" />
              Refine Answers
            </Button>
          </div>
        )}
      </CardContent>
    </Card>
  );
};
