// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@3.0.2";

// src/lib/mcp/tools/list-premixes.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@3.0.2";
import { z } from "npm:zod@^4.6.5";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.84.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-premixes.ts
var list_premixes_default = defineTool({
  name: "list_premixes",
  title: "List premixes",
  description: "List the gluten-free baking premixes available in Simple Bake Hub.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).describe("Maximum number of premixes to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("premixes").select("id, name, description, difficulty, water_amount, oil_amount").order("name", { ascending: true }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const premixes = (data ?? []).map((p) => ({
      id: p.id,
      name: p.name,
      description: p.description,
      difficulty: p.difficulty,
      waterAmount: p.water_amount,
      oilAmount: p.oil_amount
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(premixes, null, 2) }],
      structuredContent: { premixes }
    };
  }
});

// src/lib/mcp/tools/list-feeding-logs.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@3.0.2";
import { z as z2 } from "npm:zod@^4.6.5";
var list_feeding_logs_default = defineTool2({
  name: "list_feeding_logs",
  title: "List starter feedings",
  description: "List the signed-in baker's most recent sourdough starter feedings.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).describe("Maximum number of feedings to return."),
    starterName: z2.string().trim().min(1).nullable().describe("Only return feedings for this starter name, or null for all starters.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, starterName }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("feeding_logs").select(
      "id, starter_name, fed_at, flour_type, flour_amount_g, water_amount_g, temperature_celsius, rise_percentage, peak_hours, notes"
    ).order("fed_at", { ascending: false }).limit(limit);
    if (starterName) query = query.eq("starter_name", starterName);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const feedings = (data ?? []).map((f) => ({
      id: f.id,
      starterName: f.starter_name,
      fedAt: f.fed_at,
      flourType: f.flour_type,
      flourAmountG: f.flour_amount_g,
      waterAmountG: f.water_amount_g,
      temperatureCelsius: f.temperature_celsius ?? null,
      risePercentage: f.rise_percentage ?? null,
      peakHours: f.peak_hours ?? null,
      notes: f.notes ?? null
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(feedings, null, 2) }],
      structuredContent: { feedings }
    };
  }
});

// src/lib/mcp/tools/log-feeding.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@3.0.2";
import { z as z3 } from "npm:zod@^4.6.5";
var log_feeding_default = defineTool3({
  name: "log_feeding",
  title: "Log a starter feeding",
  description: "Record a sourdough starter feeding for the signed-in baker.",
  inputSchema: {
    starterName: z3.string().trim().min(1).max(100).describe("Name of the starter being fed."),
    flourType: z3.string().trim().min(1).max(100).describe("Flour used for the feeding."),
    flourAmountG: z3.number().min(0).max(1e4).describe("Flour amount in grams."),
    waterAmountG: z3.number().min(0).max(1e4).describe("Water amount in grams."),
    temperatureCelsius: z3.number().min(-20).max(80).nullable().describe("Ambient temperature in Celsius, or null if unknown."),
    notes: z3.string().trim().max(1e3).nullable().describe("Optional notes, or null.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ starterName, flourType, flourAmountG, waterAmountG, temperatureCelsius, notes }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("feeding_logs").insert({
      user_id: ctx.getUserId(),
      starter_name: starterName,
      flour_type: flourType,
      flour_amount_g: flourAmountG,
      water_amount_g: waterAmountG,
      temperature_celsius: temperatureCelsius,
      notes
    }).select("id, starter_name, fed_at").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const feeding = data ? { id: data.id, starterName: data.starter_name, fedAt: data.fed_at } : null;
    return {
      content: [
        {
          type: "text",
          text: feeding ? `Logged a feeding for ${feeding.starterName} at ${feeding.fedAt}.` : "Feeding logged."
        }
      ],
      structuredContent: { feeding }
    };
  }
});

// src/lib/mcp/tools/list-baking-sessions.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@3.0.2";
import { z as z4 } from "npm:zod@^4.6.5";
var list_baking_sessions_default = defineTool4({
  name: "list_baking_sessions",
  title: "List baking sessions",
  description: "List the signed-in baker's recent bakes, with outcome ratings and conditions.",
  inputSchema: {
    limit: z4.number().int().min(1).max(50).describe("Maximum number of bakes to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("baking_sessions").select(
      "id, premix_id, created_at, completed_at, success_rating, issues, outcome_notes, temperature_celsius, humidity_percent, oven_type"
    ).order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const sessions = (data ?? []).map((s) => ({
      id: s.id,
      premixId: s.premix_id,
      createdAt: s.created_at,
      completedAt: s.completed_at ?? null,
      successRating: s.success_rating ?? null,
      issues: (s.issues ?? []).map((issue) => issue),
      outcomeNotes: s.outcome_notes ?? null,
      temperatureCelsius: s.temperature_celsius ?? null,
      humidityPercent: s.humidity_percent ?? null,
      ovenType: s.oven_type ?? null
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(sessions, null, 2) }],
      structuredContent: { sessions }
    };
  }
});

// src/lib/mcp/tools/list-tutorials.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@3.0.2";
import { z as z5 } from "npm:zod@^4.6.5";
var list_tutorials_default = defineTool5({
  name: "list_tutorials",
  title: "List tutorials",
  description: "Search and list gluten-free baking tutorials by title or category.",
  inputSchema: {
    limit: z5.number().int().min(1).max(50).describe("Maximum number of tutorials to return."),
    search: z5.string().trim().min(1).nullable().describe("Match tutorial titles containing this text, or null for no filter."),
    category: z5.string().trim().min(1).nullable().describe("Only return tutorials in this category, or null for all categories.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, search, category }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("tutorials").select("id, title, category, content, tags, updated_at").order("title", { ascending: true }).limit(limit);
    if (search) query = query.ilike("title", `%${search}%`);
    if (category) query = query.eq("category", category);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const tutorials = (data ?? []).map((t) => ({
      id: t.id,
      title: t.title,
      category: t.category,
      content: t.content,
      tags: (t.tags ?? []).map((tag) => tag),
      updatedAt: t.updated_at
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(tutorials, null, 2) }],
      structuredContent: { tutorials }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "twszrhkovxpvosnfkdjk";
var mcp_default = defineMcp({
  name: "simple-bake-hub",
  title: "Simple Bake Hub",
  version: "0.1.0",
  instructions: "Tools for Simple Bake Hub, a gluten-free sourdough baking companion. Use `list_premixes` and `list_tutorials` for baking guidance, `list_feeding_logs` and `log_feeding` for the baker's sourdough starter, and `list_baking_sessions` for their bake history. All data belongs to the signed-in baker. Use British English and Celsius first.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_premixes_default,
    list_tutorials_default,
    list_feeding_logs_default,
    log_feeding_default,
    list_baking_sessions_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
